path:
  CODE_PATH: "./source_code/"
  DATA_PATH: "./data/"

OpenAI:
  temperature: 1.0
  model_name: "gpt-3.5-turbo"

vectorstores:
  Chroma: True
  FAISS: False

sourcecode:
  url: https://github.com/atikul-islam-sajib/ESRGAN.git

analysis:
  folder: "src"
  filenames: "py"  # In this project I just used python

chunks:
  chunk_size: 1000
  chunk_overlap: 200