path:
  CODE_PATH: "./source_code/"
  DATA_PATH: "./data/"

OpenAI:
  temperature: 1.0
  model_name: "gpt-3.5-turbo"

embeddings:
  OpenAI: True
  HuggingFace: "sentence-transformers/all-MiniLM-L6-v2"  # You can change, just check HuggingFaceHub

vectorstores:
  Chroma: True
  FAISS: False

sourcecode:
  url: https://github.com/atikul-islam-sajib/AutoEncoder.git

analysis:
  folder: "src"
  filenames: "py"  # In this project I just used python

chunks:
  chunk_size: 1000
  chunk_overlap: 200

chatExplainer:
  chat_limit: 3